
server:
  port: 8081
  servlet:
    context-path: /restaurant/api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test"
    username: root
    password: 123456

jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true